{
    "items" : [
        {
            "type"  : "Item",
            "label"   : "none",
            "name" : "Elgin Turner",
            "title" : "Mr.",
            "phone" : "444-4321",
            "nick" : "Masta Killa",
            "mbox" : "masta@wutang.com",
            "mbox_sha1sum" : "",
            "openid" : "masta.killa.openid.org",
            "homepage" : "http:\/\/www.myspace.com\/mastakilla",
            "workplaceHomepage" : "http:\/\/wutang-corp.com\/artists\/wu-artist.php?id=5",
            "weblog" : "http:\/\/themasta.blogspot.com",
            "img" : "http:\/\/upload.wikimedia.org\/wikipedia\/en\/thumb\/c\/c9\/MastaKilla.png\/220px-MastaKilla.png",
            "member" : "Wu-Tang Clan",
            "jabberID" : "masta.killa@gmail.com",
            "msnChatID" : "mastakilla@hotmail.com",
            "address-type" : "work",
            "post-office-box" : "P.O Box 768",
            "street-address" : "12 Wu Way",
            "street-address-2" : "Emerson Projects",
            "extended-address" : "",
            "region" : "New York",
            "locality" : "Brooklyn",
            "postal-code" : "33267",
            "country-name" : "%2008-%07-%09 %17:%Jul:%th",
            "class" : "public",
            "category" : "",
            "email 1" : "masta.killa@wutang-corp.com",
            "email 2" : "masta.killa@gmail.com",
            "fn" : "",
            "honorific-prefix" : "Mr.",
            "given-name" : "Elgin",
            "additional-name" : "",
            "family-name" : "Turner",
            "bday" : "%2008-%05-%26 %00:%May:%th",
            "organization-name" : "Wu-Tang Clan",
            "organization-unit-1" : "",
            "organization-unit-2" : "Unit Test Users",
            "photo" : "http:\/\/upload.wikimedia.org\/wikipedia\/en\/thumb\/c\/c9\/MastaKilla.png\/220px-MastaKilla.png",
            "tel-work" : "",
            "tel-mobile" : "666 0123"
        },
        {
            "type"  : "Item",
            "label"   : "none",
            "name" : "Tony Starks",
            "title" : "Mr.",
            "phone" : "555-4321",
            "nick" : "ironman",
            "mbox" : "tony@starksenterprises.com",
            "mbox_sha1sum" : "",
            "openid" : "tony.starks.wutang.com",
            "homepage" : "http:\/\/tonystarks.com",
            "workplaceHomepage" : "http:\/\/www.wutang.com",
            "weblog" : "http:\/\/theodore.blogspot.com",
            "img" : "",
            "member" : "Wu-Tang Clan",
            "jabberID" : "tonys@gmail.com",
            "msnChatID" : "",
            "address-type" : "work",
            "post-office-box" : "P.O Box 421",
            "street-address" : "11 Heart Street",
            "street-address-2" : "Stapleton Projects",
            "extended-address" : "",
            "region" : "Staten Island",
            "locality" : "New York",
            "postal-code" : "NY",
            "country-name" : "USA",
            "class" : "public",
            "category" : "",
            "email 1" : "tony@starksenterprises.com",
            "email 2" : "tonys@gmail.com",
            "fn" : "",
            "honorific-prefix" : "Mr.",
            "given-name" : "Tony",
            "additional-name" : "Theodore",
            "family-name" : "Starks",
            "bday" : "%2008-%05-%26 %00:%May:%th",
            "organization-name" : "Wu-Tang Clan",
            "organization-unit-1" : "%2008-%07-%09 %16:%Jul:%th",
            "organization-unit-2" : "Unit Test Users",
            "photo" : "",
            "tel-work" : "555 4321",
            "tel-mobile" : "666 9876"
        },
        {
            "type"  : "Item",
            "label"   : "none",
            "name" : "Lamont Jody Hawkins",
            "title" : "Mr.",
            "phone" : "555-9987",
            "nick" : "U-God",
            "mbox" : "ugodzilla@wutang.com",
            "mbox_sha1sum" : "",
            "openid" : "ugod.wutang.openid.org",
            "homepage" : "http:\/\/myspace.com\/u-god",
            "workplaceHomepage" : "http:\/\/www.wutang.com",
            "weblog" : "http:\/\/ugodzilla.blogspot.com",
            "img" : "",
            "member" : "Wu-Tang Clan",
            "jabberID" : "ugod@gmail.com",
            "msnChatID" : "",
            "address-type" : "work",
            "post-office-box" : "",
            "street-address" : "Stapleton Projects",
            "street-address-2" : "",
            "extended-address" : "",
            "region" : "New York",
            "locality" : "Brooklyn",
            "postal-code" : "4433213",
            "country-name" : "%2008-%07-%09 %17:%Jul:%th",
            "class" : "",
            "category" : "",
            "email 1" : "ugodzilla@wutang.com",
            "email 2" : "",
            "fn" : "Lamont Jody Hawkins",
            "honorific-prefix" : "",
            "given-name" : "",
            "additional-name" : "",
            "family-name" : "",
            "bday" : "%2008-%03-%26 %00:%Mar:%th",
            "organization-name" : "Wu-Tang Clan",
            "organization-unit-1" : "Hillside Scramblers",
            "organization-unit-2" : "Unit Test Users",
            "photo" : "",
            "tel-work" : "555 1177",
            "tel-mobile" : "+1 868 666 7754"
        }
    ]
}