<?php
// $Id$

/**
 * @file
 * Module definition for views_rdf
 *
 * @see views_rdf.views.inc
 */


function views_rdf_views_api() {
  return array(
    'api' => 2,
  );
}


/**
 * Renders a single user from a view in the
 */
// function views_rdf_sioc_render_xml_user($view_result) {
//
// }


/**
 * Strips illegal Unicode characters and encodes entities in string.
 *
 * @param $input
 *   String to process.
 * @return
 *   String with illegal characters stripped away and entities encoded.
 */
function views_rdf_strip_illegal_chars($input) {
  return check_plain(strip_tags($input));
}


/**
 * If input is a serialized date array, return a date string
 *
 * @param $input
 *   Input to check.
 * @return
 *   Either the original input or a date string.
 */
function views_rdf_is_date($input) {
  if (strpos($input, 'a:3:{s:5:"month"') !== 0) {
    return $input;
  }
  else {        // serialized date array
    $date = unserialize($input);
    return format_date(mktime(0, 0, 0, $date['month'], $date['day'], $date['year']), 'custom', DATE_ISO8601);
  }
}
