<?php
// $Id$

/**
 * @file
 * Module definition for views_json
 *
 * @see views_json.views.inc
 */


function views_json_views_api() {
  return array(
    'api' => 2,
//    'path' => drupal_get_path('module', 'views_json'),
  );
}


/**
 * Strips illegal JSON characters in identifier string.
 *
 * @param $input
 *   JSON to process.
 * @return
 *   JSON with illegal characters stripped away.
 */
function views_json_strip_illegal_chars($input) {
  $output = str_replace(array('{', '}', '[', ']', ':', ',', '"', "'", chr(47), chr(92)), '', $input);
  $output = preg_replace(
              '/[\x{80}-\x{A0}'.      // Non-printable ISO-8859-1 + NBSP
              '\x{01}-\x{1F}'.        // Non-printable ASCII characters
              '\x{0}]/u',             // NULL byte
            '', $output);

  return check_plain(strip_tags($output));
}


/**
 * Encodes special JSON characters in string
 *
 * @param $input
 *   String to process.
 * @return
 *   String with special JSON characters encoded.
 */
function views_json_encode_special_chars($input) {
  $output = str_replace(chr(92), '\\', $input);
  $output = str_replace(chr(47), '\/', $output);
  $output = str_replace('"', '\"', $output);
  $output = str_replace(chr(8), '\b', $output);
  $output = str_replace(chr(12), '\f', $output);
  $output = str_replace(chr(13) . chr(10), '\n', $output);
  $output = str_replace(chr(10), '\n', $output);
  $output = str_replace(chr(13), '\r', $output);
  $output = str_replace(chr(9), '\t', $output);
  return $output;
}


/**
 * If input is a serialized date array, return a date string
 *
 * @param $input
 *   Input to check.
 * @return
 *   Either the original input or a date string.
 */
function views_json_is_date($input) {
  if (strpos($input, 'a:3:{s:5:"month"') !== 0) {
    return $input;
  }
  else {        // serialized date array
    $date = unserialize($input);
    return format_date(mktime(0, 0, 0, $date['month'], $date['day'], $date['year']), 'custom', DATE_ISO8601);
  }
}


/**
 * Gets JSON data from a View rendered in the JSON data document style.
 *
 * This is useful for when working with a JSON view in code.
 *
 * @param $name
 *   The name of the view.
 * @param $display_id
 *   The display of the view to use.
 * @param $args
 *   The arguments to pass to the view.
 * @return
 *   The JSON object in associative array form or NULL otherwise.
 */
function views_json_get_json($name, $display_id = 'default', $args = array()) {
  $view = views_get_view($name);
  if (!is_object($view)) return NULL;

  $preview    = $view->preview($display_id, $args);
  $start_pos  = strpos($preview, '{');
  $finish_pos = strrpos($preview, '}');
  $length     = $finish_pos - $start_pos + 1;
  $json       = trim(substr($preview, $start_pos, $length));

  return json_decode($json, TRUE);
}
